/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Adc: typeof import('./src/components/adc.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Jungle: typeof import('./src/components/jungle.vue')['default']
    Mid: typeof import('./src/components/mid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Support: typeof import('./src/components/support.vue')['default']
    Synergie: typeof import('./src/components/synergie.vue')['default']
    Top: typeof import('./src/components/top.vue')['default']
  }
}
