// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Adc: typeof import('./src/components/adc.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Jungle: typeof import('./src/components/jungle.vue')['default']
    Mid: typeof import('./src/components/mid.vue')['default']
    Support: typeof import('./src/components/support.vue')['default']
    Synergie: typeof import('./src/components/synergie.vue')['default']
    Top: typeof import('./src/components/top.vue')['default']
  }
}

export { }
